### ISSUE TITLE
Improve HTTP response codes and response body

### ISSUE THREAD

**Issue by boskobezik** [tarikbrt2/Ecommerce-Spark#4]
I've got some responses where a wrong HTTP code was returned.

![Screenshot_3](https://user-images.githubusercontent.com/45120471/103028344-da304580-4557-11eb-9ae9-b0570ec5893a.png)
![Screenshot_5](https://user-images.githubusercontent.com/45120471/103028349-db617280-4557-11eb-8c14-dff8d83166ed.png)

Here you're returning a Mongoose model object, which is bad because it contains information that's irrelevant to the client. You should never reveal more details about the backend implementation that necessary.
![Screenshot_4](https://user-images.githubusercontent.com/45120471/103028347-dac8dc00-4557-11eb-852c-db0406d64b22.png)

**Comment by programmerraja** [comment]
@boskobezik  is this still open can I work on this
